const fs=await import('node:fs/promises'),path=await import('node:path'),crypto=await import('node:crypto');
const root=globalThis.POKEMONCH_ROOT||process.env.POKEMONCH_ROOT,dataPath=path.join(root,'data.json'),work=path.join(root,'.update');
const flags=new Set((globalThis.POKEMONCH_ARGS||process.env.POKEMONCH_ARGS||'').split(/\s+/).filter(Boolean)),dry=flags.has('--dry-run'),fresh=flags.has('--fresh'),verbose=flags.has('--verbose');
const SCHEMA=5,PARSER=5,defaults=['raichu','rillaboom','arcanine-hisui','gholdengo','sylveon','staraptor'];
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),atomic=async(p,s)=>{const t=`${p}.tmp-${process.pid}`;await fs.writeFile(t,s);await fs.rename(t,p)};
const cdn=u=>{try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='s-stats-platform-cdn.op.gg'}catch{return false}};
const speed=(base,points,a)=>Math.floor((base+points+20)*({raised:110,neutral:100,lowered:90}[a])/100);
const ITEM_EFFECTS={
  'choice-band':{name:'Choice Band',stage:'attack',category:'physical',modifier:0x1800},
  'choice-specs':{name:'Choice Specs',stage:'attack',category:'special',modifier:0x1800},
  'assault-vest':{name:'Assault Vest',stage:'defense',category:'special',modifier:0x1800},
  'muscle-band':{name:'Muscle Band',stage:'basePower',category:'physical',modifier:0x1199},
  'wise-glasses':{name:'Wise Glasses',stage:'basePower',category:'special',modifier:0x1199},
  'life-orb':{name:'Life Orb',stage:'final',modifier:0x14cc},
  'expert-belt':{name:'Expert Belt',stage:'final',modifier:0x1333,superEffective:true}
};
const TYPE_BOOSTS={
  'normal': ['silk-scarf','pink-bow','polkadot-bow'], 'fire':['charcoal','flame-plate'],
  'water':['mystic-water','splash-plate','sea-incense','wave-incense'], 'electric':['magnet','zap-plate'],
  'grass':['miracle-seed','meadow-plate','rose-incense'], 'ice':['never-melt-ice','icicle-plate'],
  'fighting':['black-belt','fist-plate'], 'poison':['poison-barb','toxic-plate'],
  'ground':['soft-sand','earth-plate'], 'flying':['sharp-beak','sky-plate'],
  'psychic':['twisted-spoon','mind-plate','odd-incense'], 'bug':['silver-powder','insect-plate'],
  'rock':['hard-stone','stone-plate','rock-incense'], 'ghost':['spell-tag','spooky-plate'],
  'dragon':['dragon-fang','draco-plate'], 'dark':['black-glasses','dread-plate'],
  'steel':['metal-coat','iron-plate'], 'fairy':['fairy-feather','pixie-plate']
};
for(const [type,keys] of Object.entries(TYPE_BOOSTS))for(const key of keys)
  ITEM_EFFECTS[key]={name:key,stage:'basePower',type,modifier:0x1333};
const EXCLUDED_ITEM_KEYS=new Set(['focus-sash','white-herb','mental-herb','eject-button','red-card','air-balloon']);
const itemStatus=item=>{
  const key=item.key;
  if(item.category==='berries')return{status:'excluded',reason:'一次性果子不纳入静态伤害'};
  if(item.category==='mega-stones')return{status:'excluded',reason:'超级石由形态数据处理'};
  if(key.endsWith('-seed')||key.includes('terrain-seed'))return{status:'excluded',reason:'场地种子依赖场地且会消耗'};
  if(key.endsWith('-gem')||EXCLUDED_ITEM_KEYS.has(key))return{status:'excluded',reason:'一次性或条件道具不纳入静态伤害'};
  if(ITEM_EFFECTS[key])return{status:'applied',reason:'固定倍率已按 NCP 阶段计入'};
  return{status:'unsupported',reason:'已识别但当前伤害内核未覆盖'};
};
function validate(d){if(d?.schemaVersion!==SCHEMA||d.sourceMode!=='double'||d.profiles?.length!==50||d.singleProfiles?.length!==50||!d.forms||!d.typeColors||d.damageCalc?.generation!==10)throw Error('expected schema v4 dual-mode damage dataset');const ids=new Set(d.profiles.map(x=>x.id));if(ids.size!==50)throw Error('invalid profile ids');for(const id of defaults)if(!ids.has(id))throw Error(`default missing: ${id}`);for(const p of d.profiles){if(p.sourceMode!=='double'||p.beats?.length!==30||p.loses?.length!==30||p.moves?.length!==10||p.statPoints?.length!==30||!p.formIds?.length)throw Error(`invalid doubles profile: ${p.name}`)}for(const p of d.singleProfiles)if(p.sourceMode!=='single'||p.beats?.length!==30||p.loses?.length!==30||p.moves?.length!==10)throw Error(`invalid singles profile: ${p.name}`);const mega=Object.values(d.forms).filter(x=>x.kind==='mega');if(mega.length<29||mega.some(x=>!cdn(x.image)))throw Error(`incomplete Mega catalog: ${mega.length}`)}
function validateItems(d){if(!d.damageCalc?.items?.effects||!d.damageCalc?.items?.itemCatalog)throw Error('item damage metadata missing');const catalog=Object.values(d.damageCalc.items.itemCatalog);for(const p of d.profiles)for(const item of p.heldItems){if(!item.itemKey||!item.itemName||!item.damageStatus||!['applied','excluded','unsupported'].includes(item.damageStatus))throw Error(`invalid held item: ${p.id}/${item.itemId}`);if(!catalog.some(x=>x.id===String(item.itemId)&&x.key===item.itemKey))throw Error(`orphan held item: ${p.id}/${item.itemId}`);if(item.damageStatus==='applied'&&!d.damageCalc.items.effects[item.itemKey])throw Error(`missing item effect: ${item.itemKey}`)}}
function balanced(s,start){const open=s[start],close=open==='{'?'}':open==='['?']':null;if(!close)throw Error('expected object or array');let depth=0,str=false,esc=false;for(let i=start;i<s.length;i++){const c=s[i];if(str){if(esc)esc=false;else if(c==='\\')esc=true;else if(c==='"')str=false}else if(c==='"')str=true;else if(c===open)depth++;else if(c===close&&!--depth)return s.slice(start,i+1)}throw Error('unterminated RSC value')}
function chunks(raw){const out=[];for(const m of raw.matchAll(/self\.__next_f\.push\((\[.*?\])\)<\/script>/gs))try{const a=JSON.parse(m[1]);if(typeof a[1]==='string')out.push(a[1])}catch{}return out.join('\n').replaceAll('\\"','"').replaceAll('\\u0026','&')}
function sections(s){const out={};for(const name of ['singleDetail','doubleDetail'])for(let p=s.indexOf(`"${name}":`);p>=0;p=s.indexOf(`"${name}":`,p+1)){const start=s.indexOf('{',p);try{const o=JSON.parse(balanced(s,start));if(o?.pokemon&&o?.win&&o?.lose){out[name]=o;break}}catch{}}if(!out.singleDetail||!out.doubleDetail)throw Error('single/double detail missing');return out}
function objects(s){const out=[],seen=new Set(),re=/\{"id":\d+,"key":/g;for(const m of s.matchAll(re))try{const o=JSON.parse(balanced(s,m.index)),sig=`${o.id}:${o.key}:${Object.keys(o).sort()}`;if(!seen.has(sig)){seen.add(sig);out.push(o)}}catch{}return out}
function catalogObjects(s){const out=[],seen=new Set();for(const m of s.matchAll(/\"category\":\"(?:berries|hold-items|mega-stones)\"/g))try{const start=s.lastIndexOf('{',m.index),o=JSON.parse(balanced(s,start)),sig=`${o.category}:${o.id}`;if(o.id!=null&&o.key&&!seen.has(sig)){seen.add(sig);out.push(o)}}catch{}return out}
function images(s){const out={};for(const m of s.matchAll(/\{"key":"([^"]+)","name":"([^"]+)","imageUrl":"([^"]+)"/g))out[m[1]]={name:m[2],image:m[3].replaceAll('\\u0026','&').split('?')[0]};return out}
function seasons(s){const p=s.indexOf('"seasons":[');if(p<0)throw Error('tier seasons missing');const start=s.indexOf('[',p),wrap=`{"v":${s.slice(start)}`,text=balanced(wrap,0);return JSON.parse(text).v}
function usageRows(rows,meta,keyName,hrefPart){return rows.map((x,i)=>{const o=meta.get(x.id)||{},key=o.key||String(x.id);return{rank:i+1,[keyName]:o.name||key,percent:`${x.usagePercent}%`,href:`/zh-cn/pokemon-champions/${hrefPart}/${key}`,type:o.type,typeIcon:o.type?`https://s-stats-platform-cdn.op.gg/pokemon/images/type/${o.type}.svg`:undefined,category:{physical:'物理',special:'特殊',status:'状态'}[o.category]}})}
function matchupRows(list,pokedex){return list.map((x,i)=>{const o=pokedex.get(x.key)||x;return{rank:i+1,targetId:x.key,name:o.name||x.key,href:`/zh-cn/pokemon-champions/pokedex/${x.key}`}})}
function buildProfile(base,detail,mode,meta){const {moves,natures,pokedex}=meta,p={...base,sourceMode:mode,battleStatsGroup:base.id};p.moves=usageRows(detail.moves,moves,'move','moves');p.winMoves=usageRows(detail.win.moves,moves,'move','moves');p.lossMoves=usageRows(detail.lose.moves,moves,'move','moves');p.beats=matchupRows(detail.win.pokemon,pokedex);p.loses=matchupRows(detail.lose.pokemon,pokedex);p.teammates=matchupRows(detail.team.ttog,pokedex);p.natures=detail.natures.map((x,i)=>{const n=natures.get(x.id)||{};return{rank:i+1,id:x.id,name:n.name||String(x.id),percent:`${x.usagePercent}%`,statUp:{speed:'速度',attack:'攻击',defense:'防御',spAttack:'特攻',spDefense:'特防'}[n.increased]||null,statDown:{speed:'速度',attack:'攻击',defense:'防御',spAttack:'特攻',spDefense:'特防'}[n.decreased]||null}});p.statPoints=detail.training.map((x,i)=>{const v=x.spread.split('-').map(z=>parseInt(z,16));return{rank:i+1,percent:`${x.usagePercent}%`,hp:v[0],attack:v[1],defense:v[2],spAttack:v[3],spDefense:v[4],speed:v[5]}});p.heldItems=detail.items.map((x,i)=>{const item=meta.items.get(`${x.category||'unknown'}:${x.id}`)||meta.itemsById.get(String(x.id));return{rank:i+1,itemId:String(x.id),itemKey:item?.key||'',itemName:item?.name||'',itemCategory:item?.category||'',itemEffect:item?.effect||'',percent:`${x.usagePercent}%`}});p.abilities=detail.abilities.map((x,i)=>({rank:i+1,abilityId:x.id,percent:`${x.usagePercent}%`}));const top=p.natures[0],points=p.statPoints[0],alignment=top.statUp==='速度'?'raised':top.statDown==='速度'?'lowered':'neutral';p.speedEstimate={baseSpeed:p.baseSpeed,speedStatPoints:points.speed,alignment,statPointsPercent:points.percent,nature:top.name,naturePercent:top.percent,independentTopRows:true,value:speed(p.baseSpeed,points.speed,alignment)};return p}
let task,lockHandle;await fs.mkdir(work,{recursive:true});const lock=path.join(work,'update.lock');try{lockHandle=await fs.open(lock,'wx');await lockHandle.writeFile(String(process.pid))}catch{throw Error('another update is running')}
try{const oldText=await fs.readFile(dataPath,'utf8'),old=JSON.parse(oldText);task=await taskSpace('PokemonCH OP.GG dual-mode update');const page=task.page('p1');await page.goto('https://op.gg/zh-cn/pokemon-champions/tier').catch(()=>{});const get=async url=>{const r=await page.fetch(url,{timeout:60000});if(!r.ok)throw Error(`${url}: HTTP ${r.status}`);return r.body};
const tierText=chunks(await get('https://op.gg/zh-cn/pokemon-champions/tier')),season=(seasons(tierText).find(x=>x.formats?.some(f=>f.id==='single'&&f.rankings?.length>=50)&&x.formats?.some(f=>f.id==='double'&&f.rankings?.length>=50))||seasons(tierText)[0]),formats=Object.fromEntries((season?.formats||[]).map(x=>[x.id,x.rankings.slice(0,50)]));if(formats.single?.length!==50||formats.double?.length!==50)throw Error('tier formats incomplete');
const union=[...new Set([...formats.single,...formats.double].map(x=>x.key))],done={};for(const key of union){let body;for(let n=1;n<=3;n++)try{body=chunks(await get(`https://op.gg/zh-cn/pokemon-champions/pokedex/${key}`));break}catch(e){if(n===3)throw e;await page.waitForTimeout(n*1000)}done[key]={body,details:sections(body)};if(verbose)console.log(`COLLECT ${Object.keys(done).length}/${union.length} ${key}`)}
const allText=[tierText,...Object.values(done).map(x=>x.body)].join('\n'),objs=objects(allText),img=images(allText),pokedex=new Map(objs.filter(x=>x.stats?.speed).map(x=>[x.key,x])),moves=new Map(objs.filter(x=>x.type&&x.category&&x.name).map(x=>[x.id,x])),natures=new Map(objs.filter(x=>Object.hasOwn(x,'increased')&&Object.hasOwn(x,'decreased')).map(x=>[x.id,x])),itemObjects=catalogObjects(allText),items=new Map(itemObjects.map(x=>[`${x.category}:${x.id}`,x])),itemsById=new Map(itemObjects.map(x=>[String(x.id),x])),meta={pokedex,moves,natures,items,itemsById};
const makeBase=r=>{const o=pokedex.get(r.key),im=img[r.key];if(!o||!im)throw Error(`metadata missing: ${r.key}`);return{rank:r.rank,name:r.name,slug:r.key,id:r.key,href:`/zh-cn/pokemon-champions/pokedex/${r.key}`,image:im.image,types:o.types,baseSpeed:o.stats.speed,formIds:[r.key]}};
const profiles=formats.double.map(r=>buildProfile(makeBase(r),done[r.key].details.doubleDetail,'double',meta)),singleProfiles=formats.single.map(r=>buildProfile(makeBase(r),done[r.key].details.singleDetail,'single',meta));
const forms={};for(const p of [...profiles,...singleProfiles])if(!forms[p.id]){const o=pokedex.get(p.id);forms[p.id]={id:p.id,opggId:o.id,speciesId:p.id,battleStatsGroup:p.id,name:p.name,kind:'base',baseSpeed:o.stats.speed,types:o.types,image:p.image,item:null}}
for(const [key,o] of pokedex)if(o.base_key&&forms[o.base_key]&&key!==o.base_key&&(key.startsWith('mega-')||String(o.item).includes('mega'))&&img[key])forms[key]={id:key,opggId:o.id,speciesId:o.base_key,battleStatsGroup:o.base_key,name:img[key].name||o.name,kind:'mega',baseSpeed:o.stats.speed,types:o.types,image:img[key].image,item:o.item,regulation:o.regulation};
for(const list of [profiles,singleProfiles])for(const p of list)p.formIds=[p.id,...Object.values(forms).filter(f=>f.kind==='mega'&&f.speciesId===p.id).map(f=>f.id).sort()];const typeObjects=objs.filter(x=>x.color&&x.sort!=null),typeColors=Object.fromEntries(typeObjects.map(x=>[x.key,x.color])),typeIcons=Object.fromEntries(typeObjects.map(x=>[x.key,`https://s-stats-platform-cdn.op.gg/pokemon/images/type/${x.key}.svg`]));
const oldDamage=old.damageCalc;if(!oldDamage?.moves||!oldDamage?.typeChart)throw Error('current damage metadata missing; rebuild schema v4 before updating');
const itemCatalog=Object.fromEntries(itemObjects.map(item=>[`${item.category}:${item.id}`,{id:String(item.id),key:item.key,name:item.name,category:item.category,effect:item.effect||'',affectedMoveKeys:item.affectedMoveKeys||[],affectedMoveTypeKeys:item.affectedMoveTypeKeys||[],affectedBuffEffectKeys:item.affectedBuffEffectKeys||[],regulation:item.regulation||null}]));
for(const profile of [...profiles,...singleProfiles])for(const held of profile.heldItems){
  const catalog=Object.values(itemCatalog).find(item=>item.id===String(held.itemId)&&(!held.itemKey||item.key===held.itemKey));
  if(!catalog)throw Error(`held item metadata missing: ${profile.id}/${held.itemId}`);
  Object.assign(held,{itemKey:catalog.key,itemName:catalog.name,itemCategory:catalog.category,itemEffectText:catalog.effect});
  const classification=itemStatus(catalog);
  Object.assign(held,{damageStatus:classification.status,damageReason:classification.reason});
}for(const p of [...profiles,...singleProfiles]){const source=(old.profiles||[]).find(x=>x.id===p.id)||(old.singleProfiles||[]).find(x=>x.id===p.id);for(const a of p.abilities){const mapped=source?.abilities?.find(x=>String(x.abilityId)===String(a.abilityId));if(mapped?.ncpName)Object.assign(a,{key:mapped.key,name:mapped.name,ncpName:mapped.ncpName})}for(const field of ['moves','winMoves','lossMoves'])for(const m of p[field]){const slug=m.href.split('/').pop(),dm=oldDamage.moves[slug];if(!dm)throw Error(`damage move missing: ${slug}`);Object.assign(m,{ncpName:dm.ncpName,power:dm.power,isSpread:dm.isSpread,mechanics:dm.mechanics})}}for(const [id,f] of Object.entries(forms)){const prior=old.forms?.[id];if(!prior?.baseStats)throw Error(`damage form missing: ${id}`);Object.assign(f,{ncpName:prior.ncpName,baseStats:prior.baseStats,weight:prior.weight,ncpAbility:prior.ncpAbility})}
const damageCalc={...oldDamage,items:{version:1,effects:ITEM_EFFECTS,excludedCategories:['berries','mega-stones','terrain-seed','consumable','conditional-one-use'],policy:'TOP1；固定倍率道具计入；一次性、场地依赖或未覆盖道具不计入',itemCatalog}};
const next={schemaVersion:SCHEMA,source:'https://op.gg/zh-cn/pokemon-champions/tier',sourceMode:'double',modes:{single:{implemented:false,profileField:'singleProfiles'},double:{implemented:true,profileField:'profiles'}},updated:`更新时间 ${season.formats[0].createdAt} · OP.GG M-6`,typeIcons,typeColors,damageCalc,forms,profiles,singleProfiles};validate(next);validateItems(next);const text=JSON.stringify(next),newSha=sha(text);console.log(JSON.stringify({status:dry?'DRY_RUN':'READY',singleProfiles:50,doubleProfiles:50,forms:Object.keys(forms).length,megaForms:Object.values(forms).filter(x=>x.kind==='mega').length,oldSha:sha(oldText),newSha},null,2));if(!dry){const backups=path.join(work,'backups');await fs.mkdir(backups,{recursive:true});const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\..*/,''),backup=path.join(backups,`data.${stamp}.json`);await fs.copyFile(dataPath,backup);await atomic(dataPath,text);const files=(await fs.readdir(backups)).filter(x=>x.endsWith('.json')).sort();for(const x of files.slice(0,-14))await fs.unlink(path.join(backups,x));console.log(`PUBLISHED ${dataPath}`)}await task.finish({keep:[]});task=null}finally{if(task)try{await task.finish({keep:[]})}catch{};if(lockHandle)await lockHandle.close();await fs.unlink(lock).catch(()=>{})}
